config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :aws
  devise_for :users

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
  resources :questions do
    resources :solutions, only: [:create]
  end
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require "csv"
end

app/models/awstext.rb
class Awstext < ApplicationRecord
  def self.import(path)
    list = []
    CSV.foreach(path,headers:true) do |row|
      list << {
        title:row["title"],
        content:row["content"]
      }
    end
    puts "インポート開始"
    Awstext.create!(list)
    puts "インポートに成功しました"
  rescue ActiveModel::UnknownAttributeError => invalid
    puts "インポートに失敗しました： #{invalid}"
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
    def self.import(path)
        list = []
        CSV.foreach(path, headers: true) do |row|
            list << {
                title: row["title"],
                url: row["url"]
        }
        end
        puts "データのインポートを開始しました！"
        Movie.create!(list)
        puts "データのインポートに成功しました！"
    rescue ActiveModel::UnknownAttributeError => invalid
        puts "データのインポートに失敗しました！"
    end
end

app/models/question.rb
class Question < ApplicationRecord
  # 「dependent: :destroy」：solutionsテーブルが削除されたら同時に削除
  has_many :solutions, dependent: :destroy

  validates :title, presence: true
  validates :detail, presence: true

  # rake import_csv:questions
  def self.import(path)
    list = []
    CSV.foreach(path, headers: true) do |row|
      list << {
              title:row["title"],
              detail:row["detail"]
      }
    end

    puts "インポートを開始しました"

    begin
      Question.create!(list)
      puts "インポートを完了しました"
    rescue ActiveModel::UnknownAttributeError => invalid
      puts "インポートに失敗 :#{invalid}"
    end
  end
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :question
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_controller.rb
class AwsController < ApplicationController
  def index
    @aws = Awstext.all
  end
  def show
    @aws = Awstext.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.page(params[:page]).per(10)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all.order(id: "DESC")
  end

  def create
    Question.create(question_params)
    redirect_to "/questions"
  end
  
  def show    
    @question  = Question.find_by(id:params[:id])
    @solution  = Solution.new
    @solutions = @question.solutions
  end

  

  private

  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
    
      
    
      def create
        question  = Question.find_by(id:params[:id])
        Solution.create(solution_params)
        redirect_to "/questions/#{params[:question_id]}"
      end
    
      private
      def solution_params
        params.require(:solution).permit(:detail).merge(question_id: params[:question_id])
      end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
      def block_code(code, language)
          language = language.split(':')[0] if language.present?

          case language.to_s
          when 'rb'
              lang = :ruby
          when 'yml'
              lang = :yaml
          when 'css'
              lang = :css
          when 'html'
              lang = :html
          when ''
              lang = :md
          else
              lang = language
          end

          CodeRay.scan(code, lang).div
      end
  end

  def markdown(text)
      html_render = HTMLwithCoderay.new(
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow', target: "_blank" }
      )
      options = {
          autolink: true,
          space_after_headers: true,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          tables: true,
          hard_wrap: true,
          xhtml: true,
          lax_html_blocks: true,
          strikethrough: true
      }
      markdown = Redcarpet::Markdown.new(html_render, options)
      markdown.render(text)
  end
end

app/helpers/aws_helper.rb
module AwsHelper
end

app/views/aws/index.html.erb
<div class="text-center">
    <h2>AWS講座</h2>
</div>
<p>注意！！！：AWSのEC2やRDSは有料サービスとなります。
無駄な料金を請求されないためにも、
不要なインスタンスは停止・削除をしてください。</p>
<table class="table table-striped">
  <thead class="bg-new text-white">
    <tr>
      <th scope="col" class="text-left">No.</th>
      <th scope="col" class=" text-left">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @aws.each.with_index(1) do |aws,i| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><a href ="/aws/<%=aws.id%>"><%=aws.title%></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/aws/show.html.erb
<h1>AWS講座</h1>

<% text = @aws.content %>
<%= markdown(text).html_safe %>

app/views/layouts/_header.html.erb
<nav class="nav navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href="/">Gyakuten</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    　<ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/">動画教材</a>
          <a class="dropdown-item" href="#">テキスト教材</a>
          <a class="dropdown-item" href="#">ライブコーディング</a>
          <a class="dropdown-item" href="/questions">質問集</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/aws">AWS講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">PHP講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">対談</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">情報発信</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">動画編集講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">ライティング講座</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">LINE@</a>
      </li>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item active nav-link" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: 'post nav-link nav-item active' %>
      <%= link_to '新規ユーザー登録', new_user_registration_path, class: 'post nav-link nav-item active' %>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GyakutenCloneGroup12</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class ="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/movies/index.html.erb
<div class="row d-flex justify-content-center">
  <div class="mb-5">
    <% @movies.each do |movie| %>
      <div class="text-center">
        <p><%= movie[:title] %></p>
        <div>
          <iframe width="560" height="315" <%= video_tag "#{movie[:url]}"%> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @movies %>
</div>

app/views/questions/index.html.erb
<div class = "question">
   <h2>新規投稿</h2>
   <%= form_with model:@question, url:questions_path, local: true do |f| %>
      <div class="form-group">
         <%= label_tag "form-title","【質問】" %>
         <%= f.text_area :title ,id:"form-title", class:"form-control", rows:3 %>

      </div>
      <div class="form-group">
         <p><%= label_tag "form-detail","【詳細】" %></p>
         <%= f.text_area :detail ,id:"form-detail", class:"form-control", rows:10 %>
      </div>
         <%= f.submit "送信",class:"btn btn-primary btn-block" ,id:"question-btn" %>
   <% end %>

   <% @questions.each do |question| %>
      <div class="container">
      <div class = "small-container p-3">
         <%= link_to(question_path(question.id)) do %>
               <div class="row ">
                  <div class="col-7 title-container">
                        <p><%= truncate(question.title, length: 50) %></p>
                  </div>
                  <div class="col-5">
                     <div class="text-right days">
                        <p>質問日　<%= question.created_at.strftime('%Y年%m月%d日') %></p>
                     </div>
                  </div>
               </div>
         <% end %>
      </div>
      </div>
   <% end %>
</div>

app/views/questions/show.html.erb
<p>【質問】</p>
<% title = @question.title %>
<%= markdown(title).html_safe %>
<hr>
<p>【詳細】</p>
<%  content = @question.detail %>
<%= markdown(content).html_safe %>
<hr>



<h3>【回答】</h3>
<p><% @solutions .each do |solution|%>
  <% solution = solution.detail %>
  <%= markdown(solution).html_safe %>
<% end %></p>




<h2>回答投稿</h2>
<%= form_with model:[@question,@solution], local: true do |f| %>
  <div class="form-group">
     <p><%= label_tag "form-detail","【詳細】" %></p>
     <%= f.text_area :detail ,id:"form-detail", class:"form-control", rows:10 %>
  </div>
     <%= f.submit "送信",class:"btn btn-primary btn-block" ,id:"question-btn" %>
<% end %>